name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.6
         users: actions/setup-python@v1
         with:
	   python-version: 3.6
       - name: Install dependencies
         run: |
           python3 -m pip3 install --upgrade pip
           pip3 install -r requirements.txt
       - name: Test with pytest
         run: pytest --vv
